### ISSUE TITLE
Do TrustedAdvisor items in the dashboard work with Basic tier TrustedAdvisor?

### ISSUE THREAD

**Issue by rfairburn** [deliveryhero/terraform-aws-service-quota-alarms#12]
All of the dashboards seem to say "no data" with policadvisor with basic, even when I can see quotas over 80% for things such as RDS instances when accessing TrustedAdvisor directly.  Since the dashboards show no data, we don't trigger the alarms in the alarms section, and the SNS topic configured doesn't get notified.

**Comment by max-rocket-internet** [comment]
Do you mean `TrustedAdvisor`, @rfairburn? 

To quote [here](https://docs.aws.amazon.com/awssupport/latest/user/trusted-advisor-check-reference.html):

> If you have a Basic Support and Developer Support plan, you can use the Trusted Advisor console to access all checks in the [Service limits](https://docs.aws.amazon.com/awssupport/latest/user/service-limits.html) category

**Comment by max-rocket-internet** [comment]
And you can see problems in the TA console, [here](https://us-east-1.console.aws.amazon.com/trustedadvisor/home?region=us-east-1#/category/service-limits)?

**Comment by rfairburn** [comment]
When I look at the dashboard for TrustedAdvisor items, I see no data like this:
<img width="832" alt="image" src="https://github.com/user-attachments/assets/166ca807-6d50-4fb6-8112-1ba404e00fa6">

But if I look at the same items in the TrustedAdvisor panel where you linked:

<img width="709" alt="image" src="https://github.com/user-attachments/assets/397d8aa0-5e5d-4521-ab47-1f0b00d9cac7">

This is with version 2.1 of the terraform for all modules

**Comment by max-rocket-internet** [comment]
OK. I see this:

![image](https://github.com/user-attachments/assets/5562f32d-7735-4118-9cea-ddaa3faf9b59)

**Comment by max-rocket-internet** [comment]
@rfairburn do you actually have RDS resources in those regions?

**Comment by rfairburn** [comment]
RDS is in `us-east-2` for the usage and the TrustedAdvisor looks to catch the 80% usage, but the graphs all say no data.  I am seeing a lot of refrences to us-east-1 in the data in the panel as applied even for the us-east-2 alarms making me think that something rendered improperly or my understanding of what should show up being wrong.  Here is an example from the source data for RDS.  The title region says `us-east-2`, the "Region" says "us-east-1" but everything else says us-east-1:

```
{
    "metrics": [
        [ "AWS/TrustedAdvisor", "ServiceLimitUsage", "ServiceName", "RDS", "ServiceLimit", "Cluster parameter groups", "Region", "us-east-2", { "id": "clusterparametergroups", "stat": "Maximum", "visible": false, "region": "us-east-1" } ],
        [ "...", "Clusters", ".", ".", { "id": "clusters", "stat": "Maximum", "visible": false, "region": "us-east-1" } ],
        [ "...", "DB instances", ".", ".", { "id": "dbinstances", "stat": "Maximum", "visible": false, "region": "us-east-1" } ],
        [ "...", "DB parameter groups", ".", ".", { "id": "dbparametergroups", "stat": "Maximum", "visible": false, "region": "us-east-1" } ],
        [ "...", "Event subscriptions", ".", ".", { "id": "eventsubscriptions", "stat": "Maximum", "visible": false, "region": "us-east-1" } ],
        [ "...", "Option groups", ".", ".", { "id": "optiongroups", "stat": "Maximum", "visible": false, "region": "us-east-1" } ],
        [ "...", "RDS DB Manual Snapshots", ".", ".", { "id": "rdsdbmanualsnapshots", "stat": "Maximum", "visible": false, "region": "us-east-1" } ],
        [ "...", "Read replicas per master", ".", ".", { "id": "readreplicaspermaster", "stat": "Maximum", "visible": false, "region": "us-east-1" } ],
        [ "...", "Storage quota (GB)", ".", ".", { "id": "storagequotagb", "stat": "Maximum", "visible": false, "region": "us-east-1" } ],
        [ "...", "Subnet groups", ".", ".", { "id": "subnetgroups", "stat": "Maximum", "visible": false, "region": "us-east-1" } ],
        [ "...", "Subnets per subnet group", ".", ".", { "id": "subnetspersubnetgroup", "stat": "Maximum", "visible": false, "region": "us-east-1" } ],
        [ { "expression": "clusterparametergroups*100", "label": "RDS: Cluster parameter groups", "region": "us-east-1" } ],
        [ { "expression": "clusters*100", "label": "RDS: Clusters", "region": "us-east-1" } ],
        [ { "expression": "dbinstances*100", "label": "RDS: DB instances", "region": "us-east-1" } ],
        [ { "expression": "dbparametergroups*100", "label": "RDS: DB parameter groups", "region": "us-east-1" } ],
        [ { "expression": "eventsubscriptions*100", "label": "RDS: Event subscriptions", "region": "us-east-1" } ],
        [ { "expression": "optiongroups*100", "label": "RDS: Option groups", "region": "us-east-1" } ],
        [ { "expression": "rdsdbmanualsnapshots*100", "label": "RDS: RDS DB Manual Snapshots", "region": "us-east-1" } ],
        [ { "expression": "readreplicaspermaster*100", "label": "RDS: Read replicas per master", "region": "us-east-1" } ],
        [ { "expression": "storagequotagb*100", "label": "RDS: Storage quota (GB)", "region": "us-east-1" } ],
        [ { "expression": "subnetgroups*100", "label": "RDS: Subnet groups", "region": "us-east-1" } ],
        [ { "expression": "subnetspersubnetgroup*100", "label": "RDS: Subnets per subnet group", "region": "us-east-1" } ]
    ],
    "period": 300,
    "region": "us-east-1",
    "title": "RDS: us-east-2",
    "view": "timeSeries",
    "yAxis": {
        "left": {
            "label": "Quota usage percentage",
            "max": 100,
            "min": 0,
            "showUnits": false
        }
    }
}
```

I will try and manually update the source and see if it starts displaying data properly.

If it does, I'll see if I can identify how wer got here and if-needed include a PR to address it if I can find time.

**Comment by rfairburn** [comment]
Ahh it looks like I was looking in the wrong place for this.  The metrics for AWS/TrustedAdvisor only exist with an AWS Support contract with Business support or higher.  I don't believe the account I was testing this in within my AWS Org has business support or higher.

**Comment by max-rocket-internet** [comment]
Ahh OK. So all resolved then?

**Comment by rfairburn** [comment]
I believe so.

I don't think I can justify the Business tier of trusted advisor at this time to get those metrics working.  It does appear that the ones I am most interested in would work as usage metrics, however.  I can investigate that separately.
